name: dynamic_library
description: Dart library for improving the process of loading dynamic libraries (with OS-specific load checks) and initializing Flutter Rust Bridge packages.
version: 1.1.2
homepage: https://github.com/open-runtime/dynamic_library

environment:
  sdk: '>=3.9.0 <4.0.0'


dependencies:
  flutter_rust_bridge: ^2.11.1
  path: ^1.8.0

dev_dependencies:
  runtime_ci_tooling:
    git:
      url: git@github.com:open-runtime/runtime_ci_tooling.git
      tag_pattern: "v{{version}}"
    version: ^0.23.0
  flutter_lints: ^6.0.0
  test: ^1.25.0
