[package]
name = "foo"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "foo"
crate-type = ["cdylib", "staticlib"]

[dependencies]
